trigger:
  - master

stages:
  - stage: Build
    jobs:
      - job: BuildAndTest
        steps:
          - task: Npm@1
            inputs:
              command: 'install'  # Faster and more reliable for CI

          - script: |
              npm test
            displayName: 'Run unit tests'
            continueOnError: true

          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: $(System.DefaultWorkingDirectory)/test-report.xml

          - task: PublishCodeCoverageResults@1
            displayName: 'Publish Code Coverage'
            condition: 'in(variables[''Agent.JobStatus''], ''Succeeded'')'
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/*coverage.xml'
              reportDirectory: $(System.DefaultWorkingDirectory)/coverage

          - task: ArchiveFiles@2
            displayName: 'Archive sources'
            inputs:
              rootFolderOrFile: $(Build.SourcesDirectory)
              includeRootFolder: false

          - task: CopyFiles@2
            displayName: 'Copy ARM templates'
            inputs:
              SourceFolder: deployment
              Contents: '*.json'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/templates'

  - stage: deploy
    jobs:
      - deployment: DeployWeb
        displayName: Deploy Web App
        pool:
          vmImage: 'Ubuntu-latest'
        environment:
          name: 'smarthotel-dev'  # Set your environment name here
          resourceName: myVM     # Name of the resource (like Virtual Machine)
          resourceType: virtualMachine  # Type of resource
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Hello world! Deploying to smarthotel-dev environment."
                    # You can add more commands here for your deployment logic.
                  displayName: 'Deploy to Environment'
